export default {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  AUTH: "AUTH",
  SET_LOGIN_USER: "SET_LOGIN_USER",
  SET_REGISTER_USER: "SET_REGISTER_USER",
  USER_LOGIN_FETCH_FAILED: "USER_LOGIN_FETCH_FAILED",
  USER_REGISTER_FETCH_FAILED: "USER_REGISTER_FETCH_FAILED",
  OPEN_MENU: "OPEN_MENU",
  GOOGLE_OAUTH: "GOOGLE_OAUTH",
  SET_GOOGLE_OAUTH: "SET_GOOGLE_OAUTH",
  GET_GOOGLE_OAUTH: "GET_GOOGLE_OAUTH",
  API: "API"
}

